/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ihuada_lame4android_AndroidLame */

#ifndef _Included_com_ihuada_lame4android_AndroidLame
#define _Included_com_ihuada_lame4android_AndroidLame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ihuada_lame4android_AndroidLame
 * Method:    initializeDefault
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ihuada_lame4android_AndroidLame_initializeDefault
  (JNIEnv *, jclass);

/*
 * Class:     com_ihuada_lame4android_AndroidLame
 * Method:    initialize
 * Signature: (IIIIFIIIIIIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ihuada_lame4android_AndroidLame_initialize
  (JNIEnv *, jclass, jint, jint, jint, jint, jfloat, jint, jint, jint, jint, jint, jint, jint, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     com_ihuada_lame4android_AndroidLame
 * Method:    lameEncode
 * Signature: ([S[SI[B)I
 */
JNIEXPORT jint JNICALL Java_com_ihuada_lame4android_AndroidLame_lameEncode
  (JNIEnv *, jclass, jshortArray, jshortArray, jint, jbyteArray);

/*
 * Class:     com_ihuada_lame4android_AndroidLame
 * Method:    encodeBufferInterleaved
 * Signature: ([SI[B)I
 */
JNIEXPORT jint JNICALL Java_com_ihuada_lame4android_AndroidLame_encodeBufferInterleaved
  (JNIEnv *, jclass, jshortArray, jint, jbyteArray);

/*
 * Class:     com_ihuada_lame4android_AndroidLame
 * Method:    lameFlush
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_ihuada_lame4android_AndroidLame_lameFlush
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_ihuada_lame4android_AndroidLame
 * Method:    lameClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ihuada_lame4android_AndroidLame_lameClose
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
